{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.plugin",
    "module": "lib-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "base-plugin-0.0.1.jar",
          "url": "base-plugin-0.0.1.jar",
          "size": 114872,
          "sha512": "11bae3e7dc3dc9c3fdf49535a8ebc49c2f77a7ca95e04fb63e1c031259eb7874fcda0f84a09cdcb23507637b06c91c91a5a57161fc9594372d738a28ead51be4",
          "sha256": "0eb25c26d11f5921078da6cc11e36deea1ebc89230f5f1aa5375e8c770f33c8c",
          "sha1": "7c0461e502c4e39aeae9b976a5adcff31e88096d",
          "md5": "abc121ae01c120273dda72aa01998a56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "base-plugin-0.0.1.jar",
          "url": "base-plugin-0.0.1.jar",
          "size": 114872,
          "sha512": "11bae3e7dc3dc9c3fdf49535a8ebc49c2f77a7ca95e04fb63e1c031259eb7874fcda0f84a09cdcb23507637b06c91c91a5a57161fc9594372d738a28ead51be4",
          "sha256": "0eb25c26d11f5921078da6cc11e36deea1ebc89230f5f1aa5375e8c770f33c8c",
          "sha1": "7c0461e502c4e39aeae9b976a5adcff31e88096d",
          "md5": "abc121ae01c120273dda72aa01998a56"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-plugin-0.0.1-javadoc.jar",
          "url": "base-plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "947c4463410e73d0d344c81d174f99dcbc4e4e4539caf0dc34a9f8cd641cee64a8f1a3ae1ad8745f1ce832e3c383a677fab12831bcd0da1ec9841996916ec166",
          "sha256": "76d219141df407210e1874c66d9c9553263cb1a56a87e149c0ef61e937249191",
          "sha1": "86bc5555af99987d3bb6a6588387f7ef5cc3f761",
          "md5": "594e59747b7c85a71432c073c8450d93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-plugin-0.0.1-sources.jar",
          "url": "base-plugin-0.0.1-sources.jar",
          "size": 23170,
          "sha512": "941498c10d929f6def8276fbb0e861b65bb921152144a0b8c001bd9524ec86aa06db2c6f075133976a1501d8c5a5a03f937e9ab121d66727b04bd6cfddb77b84",
          "sha256": "2b60926d989138c903e1f8c54522e743727c369fb4c98879b0ea8e4bc100228e",
          "sha1": "c026e6a3d6fb23fc37b01cc5b23c9c4d292bd439",
          "md5": "3f9e450e943c3ad36db5b2d27be203e3"
        }
      ]
    }
  ]
}
