{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.gradle.plugin",
    "module": "logger-jvm",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0.1.jar",
          "url": "logger-1.0.1.jar",
          "size": 87422,
          "sha512": "1f866e1e054f2d2bc4d2e91dc525a1a8d7727bb51f5a834d5df518b132821c014441c713ffe39542238c1cd735530ac92f2f7f0f6be2ddafe9e306b614bb3fe8",
          "sha256": "7a56e5e5a02b558d9c238e8bbf9266182f372e8e0a753fa0c0d528ec99b82d1b",
          "sha1": "1721ef22f165119911ddb0680c719828ab5c7f01",
          "md5": "1dc34efd99bb6ac6a857d387432ceb9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0.1.jar",
          "url": "logger-1.0.1.jar",
          "size": 87422,
          "sha512": "1f866e1e054f2d2bc4d2e91dc525a1a8d7727bb51f5a834d5df518b132821c014441c713ffe39542238c1cd735530ac92f2f7f0f6be2ddafe9e306b614bb3fe8",
          "sha256": "7a56e5e5a02b558d9c238e8bbf9266182f372e8e0a753fa0c0d528ec99b82d1b",
          "sha1": "1721ef22f165119911ddb0680c719828ab5c7f01",
          "md5": "1dc34efd99bb6ac6a857d387432ceb9c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0.1-javadoc.jar",
          "url": "logger-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "7146a95dd51d9f7ac235150d7cb0fd65954a74df36eb883aa6f73bf8c510c1a44a8b339b90e30c44784a5e1161b5ed681ad5496ad835e719b9de3d832f9d429e",
          "sha256": "28df8cf58ecb54dc4c5fdbaa7c7a5b05789e090c68ed2b55538fdf95dec8300c",
          "sha1": "9f4aea2f0ffbd9fb58366d6d18e277cf781de8eb",
          "md5": "267276045fee7b30589b6f6a0f30f8b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0.1-sources.jar",
          "url": "logger-1.0.1-sources.jar",
          "size": 13711,
          "sha512": "1bb1f45fcd889dae4577e9c9e7ef061eba2727475bf7f0412285822e2ef8c1a0e8e3fa48b0b11d921e31548d0bf7a48643831b27d75ca0f87c4de298ce867158",
          "sha256": "f5151548e517a52a1b63f33101a8880bbefd3d35ad58bad9d978fe6602477d86",
          "sha1": "1572cead5f0c68913642058b860b4b1be0704aee",
          "md5": "479ca48943fb3c2029c22d181b8a2eec"
        }
      ]
    }
  ]
}
