{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.gradle.plugin",
    "module": "logger-jvm",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 77423,
          "sha512": "522087e8a065f829b891799b41001e3b35ffbee177b2100d0446dc5dcb6d55680f48fae3fe3e8b1709d913bf8d6db733c37e8af73ea22e00965bfde75f92ede6",
          "sha256": "76960ca2cacdf25a0b81ae47ce1ab2c8f8f3b548f31d8973f28160dd2baf5c87",
          "sha1": "d7685d150f64a182b4ac05edaf9b741f450305ab",
          "md5": "6e2eede82aa601d5626f62103ae7a3d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 77423,
          "sha512": "522087e8a065f829b891799b41001e3b35ffbee177b2100d0446dc5dcb6d55680f48fae3fe3e8b1709d913bf8d6db733c37e8af73ea22e00965bfde75f92ede6",
          "sha256": "76960ca2cacdf25a0b81ae47ce1ab2c8f8f3b548f31d8973f28160dd2baf5c87",
          "sha1": "d7685d150f64a182b4ac05edaf9b741f450305ab",
          "md5": "6e2eede82aa601d5626f62103ae7a3d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "50ddf9b5466afa56ab236b053a771b08e97d2657e2ad9b28b729c91b8212541154133081c07c8f624cf4859b94f0674c86f769319bff33ebdddef66186aff12c",
          "sha256": "9a8cfed935b2eb8a3d1cd7d7d73b8f3683ed264fcde8b9069e9a104eba9f0ec5",
          "sha1": "240242ed7b2a754400c4944b098e17c0a8ff30eb",
          "md5": "840d01f1b4e9f91ddbc12db99c19153e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 12745,
          "sha512": "cb10b54634b5f01d7083b684e864b59e077ba2038687a36902d1dad809d8cf9b6d3a8c0da9fd3c6683f1ede11aeef77f788278c50cb9fce78f74d4545a6fb090",
          "sha256": "05f19e0b2bc0446e13211c3ba07bfa06012fa9a776e426d4e05c7898149df6af",
          "sha1": "0bb5b4128a8a667dfde3d1f147d7a7b04fc8b612",
          "md5": "afe4e0eb8f4a018ac20beb2f023324d1"
        }
      ]
    }
  ]
}
