{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 52132,
          "sha512": "1b4614f9a84cc83ba370ba2266c395152683eb72ee5aeb69d510da636f5fa3c4cd273b5de8b15bcc716d9ad6140ccb0e9c46ea5325d1c2cf07f1d1e0b50c6a3f",
          "sha256": "499bc73611c890b0bb271f504b0b93eabec9329fe94a14d350bf41c3f7ea93a0",
          "sha1": "c462d9f93d02352cca7e0e66cd885b89bb7c809c",
          "md5": "d3a6668df4eeddc8f00af3eeffebdfff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 52132,
          "sha512": "1b4614f9a84cc83ba370ba2266c395152683eb72ee5aeb69d510da636f5fa3c4cd273b5de8b15bcc716d9ad6140ccb0e9c46ea5325d1c2cf07f1d1e0b50c6a3f",
          "sha256": "499bc73611c890b0bb271f504b0b93eabec9329fe94a14d350bf41c3f7ea93a0",
          "sha1": "c462d9f93d02352cca7e0e66cd885b89bb7c809c",
          "md5": "d3a6668df4eeddc8f00af3eeffebdfff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 8877,
          "sha512": "2421640a93e5591a547e79c940f2d5703faec8e3a88e2f8bb9ef26c7b391015a92ae28db1222823eb4145ef9a849fc8a9cced31052faf7ea49cba7c05f7bca75",
          "sha256": "5ad5f6fdaf70924b22f1c6d896a40ab5d2802804a9f60224691ed17da1d821f7",
          "sha1": "f2b5753ca87459490cede4ac0d4142ab273a61e4",
          "md5": "f82d4c337daf1a244bebf597b0c18fec"
        }
      ]
    }
  ]
}
