{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 53084,
          "sha512": "732ce76098464319653934868de0ec83145abe5045f01e9bc44d6dd7ef02fd83a739b607e8a1448b1c0852d4acd72543556de66d6b2d3dd360336e16568601c1",
          "sha256": "7cc283ea316d358e0f3046b61a89d89d61506658d2e14fa0adaddfcc66e1f30e",
          "sha1": "295d5f760074148c3c00dab14346197f66f5ed64",
          "md5": "b75fe69c1da9874e1804d446c3b5bef4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 53084,
          "sha512": "732ce76098464319653934868de0ec83145abe5045f01e9bc44d6dd7ef02fd83a739b607e8a1448b1c0852d4acd72543556de66d6b2d3dd360336e16568601c1",
          "sha256": "7cc283ea316d358e0f3046b61a89d89d61506658d2e14fa0adaddfcc66e1f30e",
          "sha1": "295d5f760074148c3c00dab14346197f66f5ed64",
          "md5": "b75fe69c1da9874e1804d446c3b5bef4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 9008,
          "sha512": "51a11ff2c61843eefd7d80fdbba69de5064527aeb2952349cb0ce94c539dc2be752610e16793d83cbbf2cac958a770bff7fbe707f3941b2402e26af5b3389193",
          "sha256": "06c4bcd9aa2a9926eeae95d3ea32ae0bf8a74385a750f511290ba98dc988e0ee",
          "sha1": "ffcaa93e7a5c39fd93af42af1b2a73196a067729",
          "md5": "e9e29dc477c29339d896f1752053cdff"
        }
      ]
    }
  ]
}
