{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 50070,
          "sha512": "4e59184366736b749eca6da37ccae082b4f5889fedc2368d2d0f34e3f0b644bbced6f83f5c3bdeba2bccb7ed56ee0e6ee12dbc9486b851c66f12f64e1e68fd0b",
          "sha256": "a9d108e8cee57af720c0671643a784d8cb3e1ceb2e9174539b981354ca7a39af",
          "sha1": "58d8f8443916d5cf67eed4b7393fe4acd8345244",
          "md5": "99ce48f9c22de936cbe926478dee063c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 50070,
          "sha512": "4e59184366736b749eca6da37ccae082b4f5889fedc2368d2d0f34e3f0b644bbced6f83f5c3bdeba2bccb7ed56ee0e6ee12dbc9486b851c66f12f64e1e68fd0b",
          "sha256": "a9d108e8cee57af720c0671643a784d8cb3e1ceb2e9174539b981354ca7a39af",
          "sha1": "58d8f8443916d5cf67eed4b7393fe4acd8345244",
          "md5": "99ce48f9c22de936cbe926478dee063c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 8768,
          "sha512": "606515981b6a178a0e07241df2bfa09a05832bf576c20811b9b8556a783d22eca01ca9ecb2e1898784a30f0b82d503d40e6655fce85d43f0d3375d707007f08e",
          "sha256": "63afaebe36a1ef82cb84fe0c07861dd1f810f8a9c0f05c80d625b1a37a75770f",
          "sha1": "d974903ba0a1e69f54a871db1234600d7f373e18",
          "md5": "8f6cddf93b86e9ab74c9f127552ad1a9"
        }
      ]
    }
  ]
}
