{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 52239,
          "sha512": "395add03571fef19823a808a5c91e8bfe45dafd468a985a657a98801d6ebaa5a21a0cfca6d2a2b77fb2f568529e2374dda481a91a7cec970f68616b880cccc02",
          "sha256": "fbfb1acf484b25f4f6a01f181f6e14970d903c29411fd5ef3fc4463932b9ccba",
          "sha1": "7feb10990cee56dff28eee60d4ac40049b71ebb2",
          "md5": "6bce49b198a55d6883d23a74af68ceaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 52239,
          "sha512": "395add03571fef19823a808a5c91e8bfe45dafd468a985a657a98801d6ebaa5a21a0cfca6d2a2b77fb2f568529e2374dda481a91a7cec970f68616b880cccc02",
          "sha256": "fbfb1acf484b25f4f6a01f181f6e14970d903c29411fd5ef3fc4463932b9ccba",
          "sha1": "7feb10990cee56dff28eee60d4ac40049b71ebb2",
          "md5": "6bce49b198a55d6883d23a74af68ceaf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 8940,
          "sha512": "5206b9c97cd68289305bb0109ed080556c445744a8889813178ddd98301662165f71d97832478a703f827aef6c53d72570696b17870317150c9197f888a346da",
          "sha256": "96bf3bbadc5c1cf574ac37e4c69fbace0460aacb6f498f96804aec056822bb20",
          "sha1": "7ddeb3f8817138223fe735d7c254685ecfce6e19",
          "md5": "9a238ee4621ba8378680add87cd7ce20"
        }
      ]
    }
  ]
}
