{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 53103,
          "sha512": "3629645078053ea302862619d423b6726ed529c089f5723c84d15817903cf7ff20a59ae65b98621377c7541c1a9fc2a8cb28a65639dad5bfa6abd76d0278e964",
          "sha256": "7155300b6bb5115dd1f53a5677649559813fa18e2f2a41146942d904021fb67d",
          "sha1": "f22717497ab98b35aea102b1dd9774359dffa4b1",
          "md5": "e96c95b122f002c568ca240e8ea80342"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 53103,
          "sha512": "3629645078053ea302862619d423b6726ed529c089f5723c84d15817903cf7ff20a59ae65b98621377c7541c1a9fc2a8cb28a65639dad5bfa6abd76d0278e964",
          "sha256": "7155300b6bb5115dd1f53a5677649559813fa18e2f2a41146942d904021fb67d",
          "sha1": "f22717497ab98b35aea102b1dd9774359dffa4b1",
          "md5": "e96c95b122f002c568ca240e8ea80342"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 9028,
          "sha512": "69172072911a68ac23d8794d932beb4cf8429c371489d41a59a6a6ac94653e69e0916d3f69066ba17d7ea15d1ada912630c632020dfac0cffdddc61586c9f0a5",
          "sha256": "3329e86e3ada0b455a3229c94d55ace547317c6f1f157e813343e672840f03be",
          "sha1": "9fe84ae2b6b1cea291236f91f4a30139d3660144",
          "md5": "6c1f8ee7bd6ecf3532ffb7a95c82a1a6"
        }
      ]
    }
  ]
}
