{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yangxiaobin.jvm",
    "module": "logger",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 49864,
          "sha512": "fff600555e7953516564b0420bfd9fcdb03fabacdff22a098c81726542304b1ffcecfa22cc549f9599bd9fb6e645f6f32e605f07d766d29365c501a457a518ee",
          "sha256": "09cb85772766e81387f903f44cfa3b1e21729ddc53059dfec7962028028ea8b9",
          "sha1": "e370ba368ebaf644c600ce8321d873213e9b1b25",
          "md5": "ae5d0758b18fe38d6392b87e9d3f96c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT.jar",
          "url": "logger-1.0-SNAPSHOT.jar",
          "size": 49864,
          "sha512": "fff600555e7953516564b0420bfd9fcdb03fabacdff22a098c81726542304b1ffcecfa22cc549f9599bd9fb6e645f6f32e605f07d766d29365c501a457a518ee",
          "sha256": "09cb85772766e81387f903f44cfa3b1e21729ddc53059dfec7962028028ea8b9",
          "sha1": "e370ba368ebaf644c600ce8321d873213e9b1b25",
          "md5": "ae5d0758b18fe38d6392b87e9d3f96c7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-javadoc.jar",
          "url": "logger-1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "42e3052b24df6ad357f3d93845d58f6a6f6c13a29d608247c6246e7dca2bac0f1b8c24548d81f45477214002c0bd1d7613076840561a7685e054a1ee361db9e7",
          "sha256": "35f8ef742a7540b5479f0c369dfc28998dd5a102d71f4fc45dfab5349e8842bf",
          "sha1": "47bcb71dfed2e2caab93ebca8673bd8866f33976",
          "md5": "8dfeb8135a747474774b831b9b922712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logger-1.0-SNAPSHOT-sources.jar",
          "url": "logger-1.0-SNAPSHOT-sources.jar",
          "size": 8692,
          "sha512": "a3cc8dc53741ccb1a703b65929e2f504e78a9d597dfef6b92cc925deb5e38b52d1817d68f8425e7d1a369a649b0d0fda97846b652b6a2fddfd34be59dcba382c",
          "sha256": "b31c5dcfecf6d4c8fbfcb9ee9dd8ba945fa2fb55d4a76c1e531bc341d90e903e",
          "sha1": "36f7e0f034ad331c7d377dd50594f11a6b66c67f",
          "md5": "cd52474bc2a48d8a81d7bfd924bc4e9a"
        }
      ]
    }
  ]
}
